# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='correo',
        ),
    ]
